In [101]:
import pandas as pd

In [102]:
df = pd.read_csv("Churn_Modelling.csv")
df.shape

(10000, 14)

In [103]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [104]:
df.isnull().sum()
# null qiymatlar yo'q ekan, bu yaxshi holat.

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [105]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  str
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  str
 5   Gender           10000 non-null  str
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), str(3)
memory usage: 1.1 MB

In [106]:
df = df.drop(columns='RowNumber')

In [107]:
df = df.drop(columns='CustomerId')

In [108]:
df = df.drop(columns='Surname')

In [109]:
df.duplicated().sum()
# duplicate bo'lgan data topilmadi.

np.int64(0)

In [110]:
df.head(10)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

In [111]:
df['Gender'] = (df['Gender'] == 'Male').astype(int)

In [112]:
df = pd.get_dummies(df, columns=['Geography'], drop_first=True, dtype=int)

In [113]:
df.shape

(10000, 12)

In [114]:
df.describe()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,650.528800,0.545700,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700,0.250900,0.247700
std,96.653299,0.497932,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769,0.433553,0.431698
min,350.000000,0.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000,0.000000,0.000000
25%,584.000000,0.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000,0.000000,0.000000
50%,652.000000,1.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000,0.000000,0.000000
75%,718.000000,1.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000,1.000000,0.000000
max,850.000000,1.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000,1.000000,1.000000

In [115]:
# feature engineering qilamiz
df['HasBalance'] = (df['Balance'] > 0).astype(int)

In [116]:
from sklearn.model_selection import train_test_split

X = df.drop(columns='Exited')
y = df['Exited']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [117]:
from sklearn.preprocessing import StandardScaler
num_cols = ['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'EstimatedSalary']
scaler = StandardScaler()

X_train[num_cols] = scaler.fit_transform(X_train[num_cols])
X_test[num_cols] = scaler.transform(X_test[num_cols])

In [118]:
from sklearn.linear_model import LogisticRegression
m = LogisticRegression(max_iter=1000, random_state=42)
m.fit(X_train, y_train)
print(f"LogisticRegression train: {m.score(X_train, y_train):.4f}")
print(f"LogisticRegression test: {m.score(X_test, y_test):.4f}")

LogisticRegression train: 0.8109
LogisticRegression test: 0.8075

In [119]:
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier(max_depth=4, random_state=42)
tree.fit(X_train, y_train)
print(f"DecisionTree\ntrain_score: {tree.score(X_train, y_train)}\ntest_score: {tree.score(X_test, y_test)}")

DecisionTree
train_score: 0.85125
test_score: 0.8515

In [120]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=15)
knn.fit(X_train, y_train)
print(f"KNN\ntrain_score: {knn.score(X_train, y_train):.4f}\ntest_score: {knn.score(X_test, y_test):.4f}")

KNN
train_score: 0.8626
test_score: 0.8510

In [121]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=200, max_depth=5)
rf.fit(X_train, y_train)
print(f"RandomForest:\ntrain_score: {rf.score(X_train, y_train)}\ntest_score: {rf.score(X_test, y_test)}")

RandomForest:
train_score: 0.85375
test_score: 0.852

In [122]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

svm = SVC(kernel="rbf", C=1.0, gamma='scale')
svm.fit(X_train, y_train)
pred = svm.predict(X_test)
print(len(svm.support_))
print(f"CVM:\ntrain_score: {accuracy_score(y_train, svm.predict(X_train))}\ntest_score: {accuracy_score(y_test, pred)}")

2880
CVM:
train_score: 0.865
test_score: 0.864

In [125]:
from sklearn.model_selection import GridSearchCV
params = {'C': [0.1, 1, 10],
          'gamma': ['scale', 0.01, 0.1]}
grid = GridSearchCV(SVC(), params, cv=5, scoring='recall', n_jobs=-1)
grid.fit(X_train, y_train)
print(f"best params: {grid.best_params_}")
print(f"best score: {grid.best_score_}")

best params: {'C': 10, 'gamma': 'scale'}
best score: 0.44539877300613495

In [124]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CreditScore        10000 non-null  int64
 1   Gender             10000 non-null  int64
 2   Age                10000 non-null  int64
 3   Tenure             10000 non-null  int64
 4   Balance            10000 non-null  float64
 5   NumOfProducts      10000 non-null  int64
 6   HasCrCard          10000 non-null  int64
 7   IsActiveMember     10000 non-null  int64
 8   EstimatedSalary    10000 non-null  float64
 9   Exited             10000 non-null  int64
 10  Geography_Germany  10000 non-null  int64
 11  Geography_Spain    10000 non-null  int64
 12  HasBalance         10000 non-null  int64
dtypes: float64(2), int64(11)
memory usage: 1015.8 KB